apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  # - github.com/utilitywarehouse/k8s-sidecar-injector/manifests/base?ref=master
  - ../base
resources:
  - k8s-sidecar-injector-cert.yaml
patchesStrategicMerge:
  - k8s-sidecar-injector-patch.yaml
configMapGenerator:
  - name: k8s-sidecar-injector-configs
    files:
      - resources/sidecar-test.yaml
